Repository AntoniosBarotsis/Rss2Email, pull requests merged in 2022-10, with the labels that each got.

#15 Add tests for `get_page`.
  src/lib.rs
Labels: hacktoberfest-accepted

#16 Added env variable use if feeds.txt not specified.
  src/lib.rs
Labels: enhancement

#27 Added local `mail` command support
  rustfmt.toml
  src/email/email_provider.rs
  src/email/mail_cmd.rs
  src/email/mod.rs
  src/email/sendgrid.rs
  src/main.rs
  test-docker/Dockerfile
  test-docker/build.sh
Labels: enhancement, hacktoberfest
